[package]
name = "typing_trainer"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
crossterm = "0.29.0"
text-colorizer = "1.0.0"
csv = "1.3.1"
serde = { version = "1.0.226", features = ["derive"] }
